### ISSUE TITLE
Select tech stack

### ISSUE THREAD

**Issue by Lamb3rt** [Lamb3rt/need4food#1]
We need to choose what technologies we will be using in our project.

Frontend:
- AngularJS
- Angular 6
- Vue.js
- React

Backend:
- .NET Core
- node.js
- no backend

Database:
- Firebase
- MSSQL

**Comment by czeskij** [comment]
vue / no backend / firebase

**Comment by Lamb3rt** [comment]
Angular 6 / no backend / firebase

**Comment by jaceklabuda** [comment]
I suggest to write code using Type Script with no matter library/framework.

(no matter) / no backend / firebase

**Comment by jaceklabuda** [comment]
Decided stack:
- Angular (last) with TypeScript
- Firebase (database)
